title: Mundo das Trevas
lang: 'pt-BR'
url: "https://mundodastrevas.com"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  zines:
    output: true
    permalink: '/zines/:path'
  posts:
    output: true
    permalink: '/zines/:categories/posts/:slug'
  pages:
    output: true
    permalink: '/pages/:slug'
  forums:
    output: true
    permalink: '/forums/:slug'
  topics:
    output: true
    permalink: '/forums/:categories/topics/:slug'
  forum_posts:
    output: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "application"
